# Generated by Django 3.2.3 on 2021-05-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_total',
            field=models.IntegerField(default=2000),
        ),
    ]
