# Generated by Django 3.2.3 on 2021-05-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_product_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_total',
            field=models.IntegerField(default=20000),
        ),
    ]
